image: atlassian/default-image:4
pipelines:
  default:
    - step:
        name: "1. Single Page"
        script:
          - cd 1-single-page
          - ./generate.sh
        variables:
          API_TOKEN: $API_TOKEN
        artifacts:
          - 1-single-page/output/**
