name: 1. Single Page

on:
  push:
    paths:
      - '1-single-page/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./1-single-page
    steps:
      - uses: actions/checkout@v4
      - name: Generate
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: generate.sh
      - name: Files
        run: |
          ls
          echo ----
          ls 1-single-page
      - name: Save Output
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: 1-single-page/output/
