name: 5. List pages

on:
  push:
    paths:
      - '5-list-page/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        working-directory: ./5-list-page
        run: ./generate.sh
      - name: Save Output
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: 5-list-page/output/
