name: 7. Multiple Page Types Refactored

on:
  push:
    paths:
      - '7-multiple-page-types-refactored/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        working-directory: ./7-multiple-page-types-refactored
        run: ./generate.sh
      - name: Save Output
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: 7-multiple-page-types-refactored/output/
