name: 8. Layouts and Components

on:
  push:
    paths:
      - '8-layouts-and-components/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        working-directory: ./8-layouts-and-components
        run: ./generate.sh
      - name: Save Output
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: 8-layouts-and-components/output/
